import { OutputMap } from '@pulumi/pulumi/automation';
import { SecretsManagerClient } from '@aws-sdk/client-secrets-manager';

interface PasswordTestConfig {
  autoGeneratedPasswordName: string;
}

interface ConfigContext {
  config: PasswordTestConfig;
}

interface PulumiProgramContext {
  outputs: OutputMap;
}

interface AwsContext {
  clients: {
    secretsManager: SecretsManagerClient;
  };
}

export interface PasswordTestContext
  extends ConfigContext,
    PulumiProgramContext,
    AwsContext {}
