import { OutputMap } from '@pulumi/pulumi/automation';
import { SecretsManagerClient } from '@aws-sdk/client-secrets-manager';

interface PasswordTestConfig {
  autoGeneratedPasswordName: string;
  customPasswordName: string;
  exponentialBackOffConfig: {
    delayFirstAttempt: boolean;
    numOfAttempts: number;
    startingDelay: number;
    timeMultiple: number;
    jitter: 'full' | 'none';
  };
}

interface ConfigContext {
  config: PasswordTestConfig;
}

interface PulumiProgramContext {
  outputs: OutputMap;
}

interface AwsContext {
  clients: {
    secretsManager: SecretsManagerClient;
  };
}

export interface PasswordTestContext
  extends ConfigContext,
    PulumiProgramContext,
    AwsContext {}
