import { next as studion } from '@studion/infra-code-blocks';

const appName = 'password-test';

const autoGeneratedPassword = new studion.Password(`${appName}-auto`);
const autoGeneratePasswordValue = autoGeneratedPassword.value;

const customPassword = new studion.Password(`${appName}-custom`, {
  value: 'customPass!',
});
const customPasswordValue = customPassword.value;

export {
  autoGeneratedPassword,
  customPassword,
  autoGeneratePasswordValue,
  customPasswordValue,
};
