import { next as studion } from '@studion/infra-code-blocks';

const appName = 'password-test';

const autoGeneratedPassword = new studion.Password(`${appName}-auto`);

const customPassword = new studion.Password(`${appName}-custom`, {
  value: 'customPass!',
});

module.exports = {
  autoGeneratedPassword,
  customPassword,
};
